# Generated by Django 3.2.8 on 2021-10-28 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id_movie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('creat_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
