# Generated by Django 3.2.8 on 2021-10-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id_rent', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('recieve', models.DateTimeField()),
                ('regress', models.DateTimeField()),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rents', to='client.client')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='movies.movies')),
            ],
            options={
                'db_table': 'Rent',
                'managed': True,
                'unique_together': {('client', 'movies')},
            },
        ),
    ]
