# Generated by Django 3.2.8 on 2021-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CPF', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=90)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=150, null=True)),
                ('number_adress', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': True,
            },
        ),
    ]
